// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package data.thsql_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: tHSQL Purpose: <br>
 * Description: <br>
 * 
 * @author user@talend.com
 * @version 7.2.1.20190620_1446
 * @status
 */
public class tHSQL implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "tHSQL";
	private final String projectName = "DATA";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					tHSQL.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(tHSQL.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tFixedFlowInput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tHSQLDbOutput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tHSQLDbInput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tHSQLDbInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tHSQLDbInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFixedFlowInput_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tHSQLDbInput_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_DATA_tHSQL = new byte[0];
		static byte[] commonByteArray_DATA_tHSQL = new byte[0];

		public String Test;

		public String getTest() {
			return this.Test;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DATA_tHSQL.length) {
					if (length < 1024 && commonByteArray_DATA_tHSQL.length == 0) {
						commonByteArray_DATA_tHSQL = new byte[1024];
					} else {
						commonByteArray_DATA_tHSQL = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DATA_tHSQL, 0, length);
				strReturn = new String(commonByteArray_DATA_tHSQL, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DATA_tHSQL) {

				try {

					int length = 0;

					this.Test = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.Test, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("Test=" + Test);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tFixedFlowInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();

				/**
				 * [tHSQLDbOutput_1 begin ] start
				 */

				ok_Hash.put("tHSQLDbOutput_1", false);
				start_Hash.put("tHSQLDbOutput_1", System.currentTimeMillis());

				currentComponent = "tHSQLDbOutput_1";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						if (execStat) {
							runStat.updateStatOnConnection("row1" + iterateId, 0, 0);
						}

					}
				}

				int tos_count_tHSQLDbOutput_1 = 0;

				String url_tHSQLDbOutput_1 = null;
				url_tHSQLDbOutput_1 = "jdbc:hsqldb:file:" + "C:/xampp/htdocs/talend/data/DB" + "/" + "Test_HSQL";

				int nb_line_tHSQLDbOutput_1 = 0;
				int nb_line_update_tHSQLDbOutput_1 = 0;
				int nb_line_inserted_tHSQLDbOutput_1 = 0;
				int nb_line_deleted_tHSQLDbOutput_1 = 0;
				int nb_line_rejected_tHSQLDbOutput_1 = 0;

				int deletedCount_tHSQLDbOutput_1 = 0;
				int updatedCount_tHSQLDbOutput_1 = 0;
				int insertedCount_tHSQLDbOutput_1 = 0;
				int rejectedCount_tHSQLDbOutput_1 = 0;

				String tableName_tHSQLDbOutput_1 = "Test_table";
				boolean whetherReject_tHSQLDbOutput_1 = false;

				java.lang.Class.forName("org.hsqldb.jdbcDriver");
				String dbUser_tHSQLDbOutput_1 = "sa";

				final String decryptedPassword_tHSQLDbOutput_1 = routines.system.PasswordEncryptUtil
						.decryptPassword("ENC:[0HRQp0RAZYaBpIqJO4OtKA==]");

				String dbPwd_tHSQLDbOutput_1 = decryptedPassword_tHSQLDbOutput_1;
				java.sql.Connection conn_tHSQLDbOutput_1 = java.sql.DriverManager.getConnection(url_tHSQLDbOutput_1,
						dbUser_tHSQLDbOutput_1, dbPwd_tHSQLDbOutput_1);
				resourceMap.put("conn_tHSQLDbOutput_1", conn_tHSQLDbOutput_1);
				conn_tHSQLDbOutput_1.setAutoCommit(false);
				java.sql.DatabaseMetaData dbMetaData_tHSQLDbOutput_1 = conn_tHSQLDbOutput_1.getMetaData();
				boolean whetherExist_tHSQLDbOutput_1 = false;
				try (java.sql.ResultSet rsTable_tHSQLDbOutput_1 = dbMetaData_tHSQLDbOutput_1.getTables(null, null, null,
						new String[] { "TABLE" })) {
					while (rsTable_tHSQLDbOutput_1.next()) {
						String table_tHSQLDbOutput_1 = rsTable_tHSQLDbOutput_1.getString("TABLE_NAME");
						if (table_tHSQLDbOutput_1.equalsIgnoreCase("Test_table")) {
							whetherExist_tHSQLDbOutput_1 = true;
							break;
						}
					}
				}
				if (!whetherExist_tHSQLDbOutput_1) {
					try (java.sql.Statement stmtCreate_tHSQLDbOutput_1 = conn_tHSQLDbOutput_1.createStatement()) {
						stmtCreate_tHSQLDbOutput_1
								.execute("CREATE TABLE " + tableName_tHSQLDbOutput_1 + "(Test VARCHAR(100)  )");
					}
				}
				String insert_tHSQLDbOutput_1 = "INSERT INTO " + "Test_table" + " (Test) VALUES (?)";
				java.sql.PreparedStatement pstmt_tHSQLDbOutput_1 = conn_tHSQLDbOutput_1
						.prepareStatement(insert_tHSQLDbOutput_1);
				resourceMap.put("pstmt_tHSQLDbOutput_1", pstmt_tHSQLDbOutput_1);

				int commitEvery_tHSQLDbOutput_1 = 10000;

				int commitCounter_tHSQLDbOutput_1 = 0;

				/**
				 * [tHSQLDbOutput_1 begin ] stop
				 */

				/**
				 * [tFixedFlowInput_1 begin ] start
				 */

				ok_Hash.put("tFixedFlowInput_1", false);
				start_Hash.put("tFixedFlowInput_1", System.currentTimeMillis());

				currentComponent = "tFixedFlowInput_1";

				int tos_count_tFixedFlowInput_1 = 0;

				for (int i_tFixedFlowInput_1 = 0; i_tFixedFlowInput_1 < 1; i_tFixedFlowInput_1++) {

					row1.Test = "Talend";

					/**
					 * [tFixedFlowInput_1 begin ] stop
					 */

					/**
					 * [tFixedFlowInput_1 main ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					tos_count_tFixedFlowInput_1++;

					/**
					 * [tFixedFlowInput_1 main ] stop
					 */

					/**
					 * [tFixedFlowInput_1 process_data_begin ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					/**
					 * [tFixedFlowInput_1 process_data_begin ] stop
					 */

					/**
					 * [tHSQLDbOutput_1 main ] start
					 */

					currentComponent = "tHSQLDbOutput_1";

					// row1
					// row1

					if (execStat) {
						runStat.updateStatOnConnection("row1" + iterateId, 1, 1);
					}

					whetherReject_tHSQLDbOutput_1 = false;
					if (row1.Test == null) {
						pstmt_tHSQLDbOutput_1.setNull(1, java.sql.Types.VARCHAR);
					} else {
						pstmt_tHSQLDbOutput_1.setString(1, row1.Test);
					}

					try {
						insertedCount_tHSQLDbOutput_1 = insertedCount_tHSQLDbOutput_1
								+ pstmt_tHSQLDbOutput_1.executeUpdate();
						nb_line_tHSQLDbOutput_1++;
					} catch (java.lang.Exception e) {
						whetherReject_tHSQLDbOutput_1 = true;
						System.err.print(e.getMessage());
					}
					commitCounter_tHSQLDbOutput_1++;

					if (commitEvery_tHSQLDbOutput_1 <= commitCounter_tHSQLDbOutput_1) {

						conn_tHSQLDbOutput_1.commit();

						commitCounter_tHSQLDbOutput_1 = 0;

					}

					tos_count_tHSQLDbOutput_1++;

					/**
					 * [tHSQLDbOutput_1 main ] stop
					 */

					/**
					 * [tHSQLDbOutput_1 process_data_begin ] start
					 */

					currentComponent = "tHSQLDbOutput_1";

					/**
					 * [tHSQLDbOutput_1 process_data_begin ] stop
					 */

					/**
					 * [tHSQLDbOutput_1 process_data_end ] start
					 */

					currentComponent = "tHSQLDbOutput_1";

					/**
					 * [tHSQLDbOutput_1 process_data_end ] stop
					 */

					/**
					 * [tFixedFlowInput_1 process_data_end ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					/**
					 * [tFixedFlowInput_1 process_data_end ] stop
					 */

					/**
					 * [tFixedFlowInput_1 end ] start
					 */

					currentComponent = "tFixedFlowInput_1";

				}
				globalMap.put("tFixedFlowInput_1_NB_LINE", 1);

				ok_Hash.put("tFixedFlowInput_1", true);
				end_Hash.put("tFixedFlowInput_1", System.currentTimeMillis());

				/**
				 * [tFixedFlowInput_1 end ] stop
				 */

				/**
				 * [tHSQLDbOutput_1 end ] start
				 */

				currentComponent = "tHSQLDbOutput_1";

				if (commitCounter_tHSQLDbOutput_1 > 0) {
					conn_tHSQLDbOutput_1.commit();
				}
				if (pstmt_tHSQLDbOutput_1 != null) {
					pstmt_tHSQLDbOutput_1.close();
					resourceMap.remove("pstmt_tHSQLDbOutput_1");
				}
				resourceMap.put("statementClosed_tHSQLDbOutput_1", true);
				conn_tHSQLDbOutput_1.close();

				resourceMap.put("finish_tHSQLDbOutput_1", true);

				nb_line_deleted_tHSQLDbOutput_1 = nb_line_deleted_tHSQLDbOutput_1 + deletedCount_tHSQLDbOutput_1;
				nb_line_update_tHSQLDbOutput_1 = nb_line_update_tHSQLDbOutput_1 + updatedCount_tHSQLDbOutput_1;
				nb_line_inserted_tHSQLDbOutput_1 = nb_line_inserted_tHSQLDbOutput_1 + insertedCount_tHSQLDbOutput_1;
				nb_line_rejected_tHSQLDbOutput_1 = nb_line_rejected_tHSQLDbOutput_1 + rejectedCount_tHSQLDbOutput_1;

				globalMap.put("tHSQLDbOutput_1_NB_LINE", nb_line_tHSQLDbOutput_1);
				globalMap.put("tHSQLDbOutput_1_NB_LINE_UPDATED", nb_line_update_tHSQLDbOutput_1);
				globalMap.put("tHSQLDbOutput_1_NB_LINE_INSERTED", nb_line_inserted_tHSQLDbOutput_1);
				globalMap.put("tHSQLDbOutput_1_NB_LINE_DELETED", nb_line_deleted_tHSQLDbOutput_1);
				globalMap.put("tHSQLDbOutput_1_NB_LINE_REJECTED", nb_line_rejected_tHSQLDbOutput_1);

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null || !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row1" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("tHSQLDbOutput_1", true);
				end_Hash.put("tHSQLDbOutput_1", System.currentTimeMillis());

				/**
				 * [tHSQLDbOutput_1 end ] stop
				 */

			} // end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tFixedFlowInput_1:OnSubjobOk", "",
						Thread.currentThread().getId() + "", "", "", "", "", "");
			}

			if (execStat) {
				runStat.updateStatOnConnection("OnSubjobOk1", 0, "ok");
			}

			tHSQLDbInput_1Process(globalMap);

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFixedFlowInput_1 finally ] start
				 */

				currentComponent = "tFixedFlowInput_1";

				/**
				 * [tFixedFlowInput_1 finally ] stop
				 */

				/**
				 * [tHSQLDbOutput_1 finally ] start
				 */

				currentComponent = "tHSQLDbOutput_1";

				try {
					if (resourceMap.get("statementClosed_tHSQLDbOutput_1") == null) {
						java.sql.PreparedStatement pstmtToClose_tHSQLDbOutput_1 = null;
						if ((pstmtToClose_tHSQLDbOutput_1 = (java.sql.PreparedStatement) resourceMap
								.remove("pstmt_tHSQLDbOutput_1")) != null) {
							pstmtToClose_tHSQLDbOutput_1.close();
						}
					}
				} finally {
					if (resourceMap.get("finish_tHSQLDbOutput_1") == null) {
						java.sql.Connection ctn_tHSQLDbOutput_1 = null;
						if ((ctn_tHSQLDbOutput_1 = (java.sql.Connection) resourceMap
								.get("conn_tHSQLDbOutput_1")) != null) {
							try {
								ctn_tHSQLDbOutput_1.close();
							} catch (java.sql.SQLException sqlEx_tHSQLDbOutput_1) {
								String errorMessage_tHSQLDbOutput_1 = "failed to close the connection in tHSQLDbOutput_1 :"
										+ sqlEx_tHSQLDbOutput_1.getMessage();
								System.err.println(errorMessage_tHSQLDbOutput_1);
							}
						}
					}
				}

				/**
				 * [tHSQLDbOutput_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", 1);
	}

	public static class row2Struct implements routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_DATA_tHSQL = new byte[0];
		static byte[] commonByteArray_DATA_tHSQL = new byte[0];

		public String TEST;

		public String getTEST() {
			return this.TEST;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DATA_tHSQL.length) {
					if (length < 1024 && commonByteArray_DATA_tHSQL.length == 0) {
						commonByteArray_DATA_tHSQL = new byte[1024];
					} else {
						commonByteArray_DATA_tHSQL = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DATA_tHSQL, 0, length);
				strReturn = new String(commonByteArray_DATA_tHSQL, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DATA_tHSQL) {

				try {

					int length = 0;

					this.TEST = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.TEST, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("TEST=" + TEST);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tHSQLDbInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tHSQLDbInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row2Struct row2 = new row2Struct();

				/**
				 * [tLogRow_1 begin ] start
				 */

				ok_Hash.put("tLogRow_1", false);
				start_Hash.put("tLogRow_1", System.currentTimeMillis());

				currentComponent = "tLogRow_1";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						if (execStat) {
							runStat.updateStatOnConnection("row2" + iterateId, 0, 0);
						}

					}
				}

				int tos_count_tLogRow_1 = 0;

				///////////////////////

				final String OUTPUT_FIELD_SEPARATOR_tLogRow_1 = "|";
				java.io.PrintStream consoleOut_tLogRow_1 = null;

				StringBuilder strBuffer_tLogRow_1 = null;
				int nb_line_tLogRow_1 = 0;
///////////////////////    			

				/**
				 * [tLogRow_1 begin ] stop
				 */

				/**
				 * [tHSQLDbInput_1 begin ] start
				 */

				ok_Hash.put("tHSQLDbInput_1", false);
				start_Hash.put("tHSQLDbInput_1", System.currentTimeMillis());

				currentComponent = "tHSQLDbInput_1";

				int tos_count_tHSQLDbInput_1 = 0;

				int nb_line_tHSQLDbInput_1 = 0;
				java.sql.Connection conn_tHSQLDbInput_1 = null;
				String driverClass_tHSQLDbInput_1 = "org.hsqldb.jdbcDriver";
				java.lang.Class jdbcclazz_tHSQLDbInput_1 = java.lang.Class.forName(driverClass_tHSQLDbInput_1);
				String dbUser_tHSQLDbInput_1 = "sa";

				final String decryptedPassword_tHSQLDbInput_1 = routines.system.PasswordEncryptUtil
						.decryptPassword("ENC:[0HRQp0RAZYaBpIqJO4OtKA==]");

				String dbPwd_tHSQLDbInput_1 = decryptedPassword_tHSQLDbInput_1;

				String url_tHSQLDbInput_1 = null;
				url_tHSQLDbInput_1 = "jdbc:hsqldb:file:" + "C:/xampp/htdocs/talend/data/DB" + "/" + "Test_HSQL";

				conn_tHSQLDbInput_1 = java.sql.DriverManager.getConnection(url_tHSQLDbInput_1, dbUser_tHSQLDbInput_1,
						dbPwd_tHSQLDbInput_1);

				java.sql.Statement stmt_tHSQLDbInput_1 = conn_tHSQLDbInput_1.createStatement();

				String dbquery_tHSQLDbInput_1 = "SELECT Test_table.Test \nFROM	 Test_table";

				globalMap.put("tHSQLDbInput_1_QUERY", dbquery_tHSQLDbInput_1);
				java.sql.ResultSet rs_tHSQLDbInput_1 = null;

				try {
					rs_tHSQLDbInput_1 = stmt_tHSQLDbInput_1.executeQuery(dbquery_tHSQLDbInput_1);
					java.sql.ResultSetMetaData rsmd_tHSQLDbInput_1 = rs_tHSQLDbInput_1.getMetaData();
					int colQtyInRs_tHSQLDbInput_1 = rsmd_tHSQLDbInput_1.getColumnCount();

					String tmpContent_tHSQLDbInput_1 = null;

					while (rs_tHSQLDbInput_1.next()) {
						nb_line_tHSQLDbInput_1++;

						if (colQtyInRs_tHSQLDbInput_1 < 1) {
							row2.TEST = null;
						} else {

							row2.TEST = routines.system.JDBCUtil.getString(rs_tHSQLDbInput_1, 1, false);
						}

						/**
						 * [tHSQLDbInput_1 begin ] stop
						 */

						/**
						 * [tHSQLDbInput_1 main ] start
						 */

						currentComponent = "tHSQLDbInput_1";

						tos_count_tHSQLDbInput_1++;

						/**
						 * [tHSQLDbInput_1 main ] stop
						 */

						/**
						 * [tHSQLDbInput_1 process_data_begin ] start
						 */

						currentComponent = "tHSQLDbInput_1";

						/**
						 * [tHSQLDbInput_1 process_data_begin ] stop
						 */

						/**
						 * [tLogRow_1 main ] start
						 */

						currentComponent = "tLogRow_1";

						// row2
						// row2

						if (execStat) {
							runStat.updateStatOnConnection("row2" + iterateId, 1, 1);
						}

///////////////////////		

						strBuffer_tLogRow_1 = new StringBuilder();

						if (row2.TEST != null) { //

							strBuffer_tLogRow_1.append(String.valueOf(row2.TEST));

						} //

						if (globalMap.get("tLogRow_CONSOLE") != null) {
							consoleOut_tLogRow_1 = (java.io.PrintStream) globalMap.get("tLogRow_CONSOLE");
						} else {
							consoleOut_tLogRow_1 = new java.io.PrintStream(
									new java.io.BufferedOutputStream(System.out));
							globalMap.put("tLogRow_CONSOLE", consoleOut_tLogRow_1);
						}
						consoleOut_tLogRow_1.println(strBuffer_tLogRow_1.toString());
						consoleOut_tLogRow_1.flush();
						nb_line_tLogRow_1++;
//////

//////                    

///////////////////////    			

						tos_count_tLogRow_1++;

						/**
						 * [tLogRow_1 main ] stop
						 */

						/**
						 * [tLogRow_1 process_data_begin ] start
						 */

						currentComponent = "tLogRow_1";

						/**
						 * [tLogRow_1 process_data_begin ] stop
						 */

						/**
						 * [tLogRow_1 process_data_end ] start
						 */

						currentComponent = "tLogRow_1";

						/**
						 * [tLogRow_1 process_data_end ] stop
						 */

						/**
						 * [tHSQLDbInput_1 process_data_end ] start
						 */

						currentComponent = "tHSQLDbInput_1";

						/**
						 * [tHSQLDbInput_1 process_data_end ] stop
						 */

						/**
						 * [tHSQLDbInput_1 end ] start
						 */

						currentComponent = "tHSQLDbInput_1";

					}
				} finally {
					if (rs_tHSQLDbInput_1 != null) {
						rs_tHSQLDbInput_1.close();
					}
					if (stmt_tHSQLDbInput_1 != null) {
						stmt_tHSQLDbInput_1.close();
					}
					if (conn_tHSQLDbInput_1 != null && !conn_tHSQLDbInput_1.isClosed()) {

						conn_tHSQLDbInput_1.close();

					}
				}
				globalMap.put("tHSQLDbInput_1_NB_LINE", nb_line_tHSQLDbInput_1);

				ok_Hash.put("tHSQLDbInput_1", true);
				end_Hash.put("tHSQLDbInput_1", System.currentTimeMillis());

				/**
				 * [tHSQLDbInput_1 end ] stop
				 */

				/**
				 * [tLogRow_1 end ] start
				 */

				currentComponent = "tLogRow_1";

//////
//////
				globalMap.put("tLogRow_1_NB_LINE", nb_line_tLogRow_1);

///////////////////////    			

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null || !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row2" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("tLogRow_1", true);
				end_Hash.put("tLogRow_1", System.currentTimeMillis());

				/**
				 * [tLogRow_1 end ] stop
				 */

			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tHSQLDbInput_1 finally ] start
				 */

				currentComponent = "tHSQLDbInput_1";

				/**
				 * [tHSQLDbInput_1 finally ] stop
				 */

				/**
				 * [tLogRow_1 finally ] start
				 */

				currentComponent = "tLogRow_1";

				/**
				 * [tLogRow_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tHSQLDbInput_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean enableLogStash;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final tHSQL tHSQLClass = new tHSQL();

		int exitCode = tHSQLClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = tHSQL.class.getClassLoader()
					.getResourceAsStream("data/thsql_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = tHSQL.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				// defaultProps is in order to keep the original context value
				if (context != null && context.isEmpty()) {
					defaultProps.load(inContext);
					context = new ContextProperties(defaultProps);
				}

				inContext.close();
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tFixedFlowInput_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tFixedFlowInput_1) {
			globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", -1);

			e_tFixedFlowInput_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : tHSQL");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--monitoring=")) {// for trunjob call
			enableLogStash = "true".equalsIgnoreCase(arg.substring(13));
		}

		if (!enableLogStash) {
			enableLogStash = "true".equalsIgnoreCase(System.getProperty("monitoring"));
		}
	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 48613 characters generated by Talend Open Studio for Data Integration on the
 * 2020/03/01 18:57:02 JST
 ************************************************************************************************/